# Generated by Django 5.2.6 on 2025-09-22 11:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=50)),
                ('annee_academique', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=10)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('matricule', models.CharField(max_length=50, null=True)),
                ('profile_eleve', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=100)),
                ('trimestre', models.IntegerField()),
                ('valeur', models.FloatField()),
                ('type_note', models.CharField(max_length=20)),
                ('moyenne_interrogations', models.FloatField(blank=True, null=True)),
                ('moyenne_devoirs', models.FloatField(blank=True, null=True)),
                ('moyenne_generale', models.FloatField(blank=True, null=True)),
                ('moyenne_trimestrielle', models.FloatField(blank=True, default=0.0, null=True)),
                ('rang', models.IntegerField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
                ('annee_academique', models.CharField(blank=True, max_length=10, null=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.eleve')),
            ],
        ),
    ]
