# Generated by Django 5.2.7 on 2025-10-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='telephone_parent',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
