# Generated by Django 5.2.7 on 2025-10-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_eleve_telephone_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='email_parent',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
