# Generated by Django 5.2.7 on 2025-11-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_eleve_email_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='nationalite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
