# Generated by Django 5.2.7 on 2025-11-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_eleve_date_naissance_eleve_lieu_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='coin_droit',
            field=models.ImageField(blank=True, null=True, upload_to='cartes/recto/'),
        ),
        migrations.AddField(
            model_name='login',
            name='fond_verso',
            field=models.ImageField(blank=True, null=True, upload_to='cartes/verso/'),
        ),
    ]
