# Generated by Django 5.2.7 on 2025-12-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_enseignant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enseignant',
            old_name='classe',
            new_name='classes',
        ),
    ]
