# Generated by Django 5.2.7 on 2025-12-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_classe_enseignant_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='otp_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
