# Generated by Django 5.2.7 on 2025-12-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_enseignant_otp_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='matiere',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='matieres',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
