# Generated by Django 5.2.7 on 2025-12-08 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_enseignant_matiere_enseignant_matieres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enseignant',
            old_name='matieres',
            new_name='matiere',
        ),
    ]
