# Generated by Django 5.2.7 on 2025-12-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_matieres_enseignant_matiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='matiere',
            field=models.CharField(max_length=200),
        ),
    ]
