# Generated by Django 5.2.7 on 2025-12-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_enseignant_matiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='matiere',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
