# Generated by Django 5.2.7 on 2025-12-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_enseignant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='user',
        ),
    ]
