# Generated by Django 5.2.7 on 2025-12-11 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_enseignant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('present', models.BooleanField(default=True)),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.eleve')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.enseignant')),
            ],
        ),
    ]
