# Generated by Django 5.2.7 on 2025-12-11 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_presence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence',
            name='eleve',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='heure_debut',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='heure_fin',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='motif',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='present',
        ),
        migrations.AddField(
            model_name='presence',
            name='etat',
            field=models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presence',
            name='horaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.horaire'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='classe',
            field=models.CharField(max_length=100),
        ),
    ]
