# Generated by Django 5.2.7 on 2025-12-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='motif',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
