# Generated by Django 5.2.7 on 2025-12-11 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_presence_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='eleve',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.eleve'),
            preserve_default=False,
        ),
    ]
