# Generated by Django 5.2.7 on 2025-12-12 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_presence_eleve'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classe',
        ),
    ]
