# Generated by Django 5.2.7 on 2025-12-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_delete_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='email_parent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='telephone_parent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
